version: '3'
services:
  db:
    image: mysql:5.7
    container_name: OSdatabase
    restart: always
    environment:
      MYSQL_DATABASE: 'db'

      MYSQL_USER: 'root'

      MYSQL_PASSWORD: 'root'

      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - '7000:3306'

      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: